d_dlib/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'',include('libman.urls',namespace='libman')),
    url(r'^admin/', include(admin.site.urls)),
]

libman/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$',views.index, name='index'),
    url(r'^(?P<bookisbn>[0-9-]+)/$',views.details, name='details'),
    url(r'^delete/$',views.delete,name='delete'),
    url(r'^edit/$',views.edit,name='edit'),
    url(r'^add_book/$',views.add_book,name='add_book'),
    url(r'^add_author/$',views.add_author,name='add_author'),
]

libman/models.py
from django.db import models
class Book(models.Model):
    ISBN=models.CharField(max_length=100,primary_key=True)
    Title=models.CharField(max_length=100)
    AuthorID=models.ForeignKey('Author')
    Publisher=models.CharField(max_length=100)
    PublishDate=models.DateField()
    Price=models.FloatField()
    def __str__(self):
        return self.ISBN

class Author(models.Model):
    AuthorID=models.CharField(max_length=50,primary_key=True)
    Name=models.CharField(max_length=50)
    Age=models.IntegerField()
    Country=models.CharField(max_length=50)
    def __str__(self):
        return self.AuthorID

# Create your models here.

libman/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from .models import Book, Author

add=[False,False]
def index(request):
    book_list=Book.objects.all()
    author_list=Author.objects.all()
    context={'book_list':book_list,'author_list':author_list}
    if request.method == 'POST':
        search_name = request.POST.get('author_name','')
        try:
            author = Author.objects.get(Name=search_name)
            book_list_of_author = Book.objects.filter(AuthorID=author.AuthorID)
            context = {'book_list': book_list,'author_lib':book_list_of_author,'author_name':author.Name,'author_list':author_list}
        except:
            book_list_of_author = ['empty']
            context = {'book_list': book_list,'author_empty':book_list_of_author,'author_name':search_name,'author_list':author_list}
    if add[0]:
        if add[1]:
            context['bad_parameters']=['not_empty']
            add[0]=False
            add[1]=False
        else:
            add[0]=False
            add[1]=False
            pass
    else:
        add[0]=False
        add[1]=False
        pass
    return render(request,'libman/index.html',context)

update_book_list=[]
def edit(request):
    if request.method=='GET':
        pass
        book=Book.objects.get(ISBN=request.GET.get('update_book_ISBN'))
        update_book_list.append(book)
        author_list=Author.objects.all()
        context={'book':book,'author_list':author_list}
        return render(request,'libman/edit.html',context)
    else:
        try:
            book=update_book_list[-1]
            author=Author.objects.get(AuthorID=request.POST.get('update_book_authorid'))
            book.AuthorID = author
            book.Publisher = request.POST.get('update_book_publisher')
            book.PublishDate = request.POST.get('update_book_publishdate')
            book.Price = request.POST.get('update_book_price')
            book.save()
            return HttpResponseRedirect('/')
        except:
            return render(request,'libman/edit.html',{'bad_parameters':['not_empty']})

def details(request, bookisbn):
    book=Book.objects.get(ISBN=bookisbn)
    author=Author.objects.get(AuthorID=book.AuthorID)
    context={'book':book,'author':author}
    return render(request,'libman/details.html',context)

def delete(request):
    try:
        Book.objects.get(ISBN=request.GET.get('delete_book_ISBN')).delete()
    except:
        pass
    return HttpResponseRedirect('/')

def add_book(request):
    add[0]=True
    get=request.GET
    try:
        new_book=Book(
            ISBN=get['add_book_isbn'],
            Title=get['add_book_title'],
            AuthorID=Author.objects.get(AuthorID=get['add_book_authorid']),
            Publisher=get['add_book_publisher'],
            PublishDate=get['add_book_publishdate'],
            Price=get['add_book_price']
        )
        new_book.save()
        add[1]=False
        return HttpResponseRedirect('/')
    except:
        add[1]=True
        return HttpResponseRedirect('/')

def add_author(request):
    if request.method=='GET':
        return render(request,'libman/add_author.html',{})
    else:
        post=request.POST
        try:
            new_author=Author(
                AuthorID=post['AuthorID'],
                Name=post['Name'],
                Age=post['Age'],
                Country=post['Country']
            )
            new_author.save()
            return HttpResponseRedirect('/')
        except:
            return render(request,'libman/add_author.html',{'bad_parameters':['not_empty']})
        
# Create your views here.

libman/templates/libman/add_author.html
<!DOCTYPE html>
<html lang="en-us">
    <title>Add author</title>
<head>
    <title>Add author</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
</head>

<body class="popup  app-libman model-author change-form">
    <!-- Container -->
    {% if bad_parameters %}
    <h1 style='margin-left:20px;color:red;'>Your author's info is not well formatted. Please try again!</h1>
    {% endif %}
    <div id="container">
        <div id="content" class="colM">
            <h1>Add author</h1>
            <div id="content-main">
                <form action="." method="post" id="author_form" novalidate>
                    {% csrf_token %}
                    <div>
                        <input type="hidden" name="_popup" value="1" />
                        <input type="hidden" name="_to_field" value="AuthorID" />
                        <fieldset class="module aligned ">
                            <div class="form-row field-AuthorID">
                                <div>
                                    <label class="required" for="id_AuthorID">AuthorID:</label>
                                    <input class="vTextField" id="id_AuthorID" maxlength="50" name="AuthorID" type="text" placeholder='Integer'/>
                                </div>
                            </div>
                            <div class="form-row field-Name">
                                <div>
                                    <label class="required" for="id_Name">Name:</label>
                                    <input class="vTextField" id="id_Name" maxlength="50" name="Name" type="text" />
                                </div>
                            </div>
                            <div class="form-row field-Age">
                                <div>
                                    <label class="required" for="id_Age">Age:</label>
                                    <input class="vIntegerField" id="id_Age" name="Age" type="text" placeholder='Integer'/>
                                </div>
                            </div>
                            <div class="form-row field-Country">
                                <div>
                                    <label class="required" for="id_Country">Country:</label>
                                    <input class="vTextField" id="id_Country" maxlength="50" name="Country" type="text" />
                                </div>
                            </div>
                        </fieldset>
                        <div class="submit-row">
                            <input type="submit" value="Save" class="default" name="_save" />
                            <a href="/" class="default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            <br class="clear" />
        </div>
        <!-- END Content -->
        <div id="footer"></div>
    </div>
    <!-- END Container -->
</body>

</html>

libman/templates/libman/details.html
<!DOCTYPE html>
<html>
    {% if book %}
    <title>Details of {{ book.Title }}</title>
    {% endif %}
<head>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
</head>

<body>
    {% if book %}
    <div id="content" class="colM">
        <div id="content-main">
                <div>
                    <fieldset class="module aligned ">
                        <div class="form-row field-ISBN">
                            <div>
                                <label class="required" for="id_ISBN">ISBN:</label>
                                {{ book.ISBN }}
                            </div>
                        </div>
                        <div class="form-row field-Title">
                            <div>
                                <label class="required" for="id_Title">Title:</label>
                                {{ book.Title }}
                            </div>
                        </div>
                        <div class="form-row field-AuthorID">
                            <div>
                                <label class="required" for="id_AuthorID">AuthorID:</label>
                                <div class="related-widget-wrapper">
                                    {{book.AuthorID}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-Publisher">
                            <div>
                                <label class="required" for="id_Publisher">Publisher:</label>
                                {{ book.Publisher }}
                            </div>
                        </div>
                        <div class="form-row field-PublishDate">
                            <div>
                                <label class="required" for="id_PublishDate">PublishDate:</label>
                                {{ book.PublishDate }}
                            </div>
                        </div>
                        <div class="form-row field-Price">
                            <div>
                                <label class="required" for="id_Price">Price:</label>
                                {{ book.Price }}
                            </div>
                        </div>
                    </fieldset>
                </div>
        </div>
        <br class="clear" />
    </div>
    {% endif %}
    {% if author %}
    <div id="container">
        <!-- Content -->
        <div id="content" class="colM">
            <div id="content-main">
                    <div>
                        <fieldset class="module aligned ">
                            <div class="form-row field-AuthorID">
                                <div>
                                    <label class="required" for="id_AuthorID">AuthorID:</label>
                                    {{ author.AuthorID }}
                                </div>
                            </div>
                            <div class="form-row field-Name">
                                <div>
                                    <label class="required" for="id_Name">Name:</label>
                                    {{ author.Name }}
                                </div>
                            </div>
                            <div class="form-row field-Age">
                                <div>
                                    <label class="required" for="id_Age">Age:</label>
                                    {{ author.Age }}
                                </div>
                            </div>
                            <div class="form-row field-Country">
                                <div>
                                    <label class="required" for="id_Country">Country:</label>
                                    {{ author.Country }}
                                </div>
                            </div>
                        </fieldset>
                    </div>
            </div>
            <br class="clear" />
        </div>
        <div id="footer"><a href="/" class="default" style='font-size:50px;'>Back</a></div>
    </div>
    {% endif %}
</body>

</html>

libman/templates/libman/edit.html
<!DOCTYPE html>
<html>
    {% if book %}
    <title>Edit {{book.Title }}</title>
    {% endif %}
<head>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
</head>

<body>
    {% if bad_parameters %}
    <h1 style='margin-left:20px;color:red;'>Your book's info is not well formatted. Please try again!</h1>
    {% endif %}
    {% if book %}
    <div id="content" class="colM">
        <div id="content-main">
            <form action="." method="post" id="book_form" novalidate>
                {% csrf_token %}
                <div>
                    <fieldset class="module aligned ">
                        <div class="form-row field-ISBN">
                            <div>
                                <label class="required" for="id_ISBN">ISBN:</label>
                                {{ book.ISBN }}
                            </div>
                        </div>
                        <div class="form-row field-Title">
                            <div>
                                <label class="required" for="id_Title">Title:</label>
                                {{ book.Title }}
                            </div>
                        </div>
                        <div class="form-row field-AuthorID">
                            <div>
                                <label class="required" for="id_AuthorID">AuthorID:</label>
                                <div class="related-widget-wrapper">
                                    {{book.AuthorID}}
                                    <select name='update_book_authorid'>
                                        {% for author in author_list %}
                                        <option value={{author.AuthorID}}>{{author.AuthorID}}: {{author.Name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-Publisher">
                            <div>
                                <label class="required" for="id_Publisher">Publisher:</label>
                                <input name='update_book_publisher' type='text' value='{{ book.Publisher }}' />
                            </div>
                        </div>
                        <div class="form-row field-PublishDate">
                            <div>
                                <label class="required" for="id_PublishDate">PublishDate:</label>
                                {{ book.PublishDate }}
                                <input name='update_book_publishdate' type='text' placeholder='Format: yyyy-mm-dd' />
                            </div>
                        </div>
                        <div class="form-row field-Price">
                            <div>
                                <label class="required" for="id_Price">Price:</label>
                                <input name='update_book_price' type='text' value='{{ book.Price }}' />
                            </div>
                        </div>
                    </fieldset>
                    <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="save">
                        <a href="/" class="default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
        <br class="clear" />
    </div>
    {% endif %}
</body>

</html>

libman/templates/libman/index.html
<!DOCTYPE html>
<html>
<title>d_d Book Manager</title>

<head>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
</head>

<body>
    <h1 style='font-size:50px;margin-top:20px;margin-bottom:50px;margin-left:30%;'>d_d Book Manager</h1> {% if book_list %} {% csrf_token %}
    <table>
        {% for i in book_list %}
        <tr>
            <td>
                <ul>
                    <li><a href="{% url 'libman:details' i.ISBN %}">{{ i.Title }}</a></li>
                </ul>
            </td>
            <td>
                <form action='delete/' method='GET'>
                    <input type='hidden' name='delete_book_ISBN' value={{ i.ISBN }} />
                    <input type='submit' value='Delete' />
                </form>
            </td>
            <td>
                <form action='edit/' method='GET'>
                    <input type='hidden' name='update_book_ISBN' value={{ i.ISBN }} />
                    <input type='submit' value='Edit' />
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No books are available.</p>
    {% endif %}
    <div id="content" class="colM">
        <div id="content-main" style='margin-bottom:20px;'>
            <form action="." method='POST' id='author_search'>
                {% csrf_token %}
                <input type='text' name='author_name' />
                <input type='submit' value='Author Search' />
            </form>
            <label>
                Exist Authors: {% for author in author_list %} {{author.Name}} {% endfor %}
            </label>
            {% if author_lib %}
            <p>Author {{author_name}}'s book(s)</p>
            <ul>
                {% for j in author_lib %}
                <li><a href="{% url 'libman:details' j.ISBN %}">{{ j.Title }}</a></li>
                {% endfor %}
            </ul>
            {% endif %} {% if author_empty %}
            <p>Author {{author_name}} not found.</p>
            {% endif %}
        </div>
    </div>
    {% if bad_parameters %}
    <h1 style='margin-left:20px;color:red;'>Your book's info is not well formatted. Please try again!</h1>
    {% endif %}
    <div id="content" class="colM">
        <div id="content-main">
            <form action="add_book/" method="GET" id="new_book_form" novalidate>
                <input type='hidden' name='csrfmiddlewaretoken' value='ruGXkxOX0knTGEVHiHgM4OzPXj2RGojf' />
                <div>
                    <fieldset class="module aligned ">
                        <div class="form-row field-ISBN">
                            <div>
                                <label class="required" for="id_ISBN">ISBN:</label>
                                <input name='add_book_isbn' type='text' />
                            </div>
                        </div>
                        <div class="form-row field-Title">
                            <div>
                                <label class="required" for="id_Title">Title:</label>
                                <input name='add_book_title' type='text' />
                            </div>
                        </div>
                        <div class="form-row field-AuthorID">
                            <div>
                                <label class="required" for="id_AuthorID">AuthorID:</label>
                                <div class="related-widget-wrapper">
                                    <select name='add_book_authorid'>
                                        {% for author in author_list %}
                                        <option value={{author.AuthorID}}>{{author.AuthorID}}: {{author.Name}}</option>
                                        {% endfor %}
                                    </select>
                                    <a class="related-widget-wrapper-link add-related" id="add_author" href="add_author/" title="Add another author">
                                        <img src="/static/admin/img/icon_addlink.gif" width="10" height="10" alt="Add">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-Publisher">
                            <div>
                                <label class="required" for="id_Publisher">Publisher:</label>
                                <input name='add_book_publisher' type='text' />
                            </div>
                        </div>
                        <div class="form-row field-PublishDate">
                            <div>
                                <label class="required" for="id_PublishDate">PublishDate:</label>
                                <input name='add_book_publishdate' type='text' placeholder='Format: yyyy-mm-dd' />
                            </div>
                        </div>
                        <div class="form-row field-Price">
                            <div>
                                <label class="required" for="id_Price">Price:</label>
                                <input name='add_book_price' type='text' />
                            </div>
                        </div>
                    </fieldset>
                    <div class="submit-row">
                        <input type="submit" value="Add Book" class="default" name="add">
                    </div>
                </div>
            </form>
        </div>
        <br class="clear" />
    </div>
    </div>
</body>

</html>